server:
    port: ${PORT:8761} # Indicate the default PORT where this service will be started

spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false # telling the server not to register himself in the server
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 # wait time for subsequent sync